name: 'scala-cli-setup-action'
description: 'Use Scala CLI to run your Scala code'
author: 'Alexey Alekhin'
branding:
  icon: 'anchor'
  color: 'green'
inputs:
  scala-cli-version:
    description: 'Version of scala-cli to install ("latest" to install the latest version)'
    required: false
  jvm:
    description: 'JVM to install (leave empty to use default)'
    required: false
    default: 'temurin:17'
  apps:
    description: 'Applications to install'
    required: false
    default: 'sbtn'
outputs:
  cs-version:
    description: 'Version of the installed Coursier'
  scala-cli-version:
    description: 'Version of the installed Scala CLI'
runs:
  using: 'node12'
  main: 'dist/index.js'
