on:
  push:
    branches:
    - "pr-trigger-test"

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SCALA_CLI_SETUP_INTERNAL_KEY }}
          ref: pr-trigger
      - name: Reset main branch
        run: |
          git fetch origin pr-trigger-test:pr-trigger-test
          git reset --hard pr-trigger-test
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: pr-trigger-test
          commit-message: Update ScalaCLI
          author: GitHub <noreply@github.com>
          delete-branch: true
          title: Update ScalaCLI

