on:
  push:
    branches:
    - "update-scala-cli-setup-*"

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SCALA_CLI_SETUP_INTERNAL_KEY }}
          ref: main-test
      - name: Reset main branch
        run: |
          git fetch origin update-scala-cli-setup-0.1.4:update-scala-cli-setup-0.1.4
          git reset --hard update-scala-cli-setup-0.1.4    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update-scala-cli

